config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: "static_pages#home"
    get "/about", to: "static_pages#about"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :account_activations, only: [:edit]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  attr_reader :remember_token
  attr_accessor :activation_token
  before_save :email_downcase
  before_create :create_activation_digest
  has_secure_password

  validates :name,  presence: true,
    length: {maximum: Settings.name_max_length}
  validates :email, presence: true,
    length: {maximum: Settings.email_max_length},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :password, presence: true,
    length: {minimum: Settings.password_min_length}, allow_nil: true

  def remember
    @remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end

  def forget
    update_attributes remember_digest: nil
  end

  def current_user? user
    user == self
  end

  def activated
    update_columns activated: true, activated_at: Time.zone.now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  class << self
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  private

  def email_downcase
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest activation_token
  end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    user = User.find_by email: params[:email]
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activated
      log_in user
      flash[:success] = t "account_activated"
      redirect_to user
    else
      flash[:danger] = t "account_activate_invalid"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def hello
    render html: "hello , world!"
  end
  before_action :set_locale
  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by email: params[:session][:email].downcase
    if @user&.authenticate params[:session][:password]
      if @user.activated?
        log_in @user
        remember_me
        redirect_back_or @user
      else
        message  = t "activation_message1"
        message += t "activation_message2"
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = t ".error_login"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  def remember_me
    params[:session][:remember_me] == "1" ? remember(@user) : forget(@user)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :find_user, only: [:edit, :show, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  def index
    @users = User.where(activated: true).paginate page: params[:page],
                           per_page: Settings.total_user_per_page
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = t "activation_mesage"
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    redirect_to(root_url) && return unless @user.activated == true
  end

  def edit; end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "update_mesage"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    flash[:success] = if @user.destroy
                        t "delete_mesage_success"
                      else
                        t "delete_mesage_failed"
                      end
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user)
          .permit :name, :email, :password, :password_confirmation
  end

  def logged_in_user
    return if logged_in?
    store_location
    flash[:danger] = t "login_mesage"
    redirect_to login_url
  end

  def correct_user
    redirect_to root_path unless @user.current_user? current_user
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

  def find_user
    @user = User.find_by id: params[:id]

    return if @user

    flash[:danger] = t "not_found"
    redirect_to root_path
  end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t "en_title"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def logged_in?
    current_user.present?
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user&.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to session[:forwarding_url] || default
    session.delete :forwarding_url
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: Settings.gravatar_size
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".content_footer_1" %>
    <a href="http://www.railstutorial.org/">
      <%= t ".link_name_footer" %>
    </a>
    <%= t ".content_footer_2" %>
    <a href="http://www.michaelhartl.com/">
      <%= t ".link_name_footer_end" %>
    </a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".contact"), contact_path %></li>
      <li>
        <a href="http://news.railstutorial.org/">
          <%= t ".new" %>
        </a>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".title"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".user"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle",
              data: {toggle: "dropdown"} do %>
              <%= t ".account" %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".log_in"), login_path %></li>
        <% end %>
        <li><%= link_to t(".en_language"), locale:"en" %></li>
        <li><%= link_to t(".vi_language"), locale:"vi" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".form_container"%>
      <%= pluralize @user.errors.count, t(".error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide :title, t(".title_about") %>
<h1><%= t ".title_about" %></h1>
<p>
  <%= t ".content_about_1" %>
  <a href="http://www.railstutorial.org/">
    <em><%= t ".link_name_about" %></em>
  </a>
  <%= t ".content_about_2" %>
  <a href="http://www.railstutorial.org/book">
    <%= t ".link_name_about_1" %>
  </a>
  <%= t ".content_about_3" %>
  <a href="http://screencasts.railstutorial.org/">
    <%= t ".link_name_about_2" %>
  </a>
  <%= t ".content_about_4" %>
  <a href="http://rubyonrails.org/">
    <%= t ".link_name_about_3" %>
  </a>.
  <%= t ".content_about_end" %>
</p>
<b>
  </br>
  </br>
  <%= link_to t("back"), root_path %>
</b>

app/views/static_pages/contact.html.erb
<% provide :title, t(".title_contact") %>
<h1><%= t ".title_contact" %></h1>
<p>
  <%= t ".content_contact" %>
  <a href="http://www.railstutorial.org/contact">
    <%= t ".link_name_contact" %>
  </a>.
</p>
<b>
  </br>
  </br>
  <%= link_to t("back"), root_path %>
</b>

app/views/static_pages/help.html.erb
<% provide :title, t(".title_help") %>
<h1><%= t ".title_help" %></h1>
<p>
  <%= t ".content_help_1" %>
  <a href="http://www.railstutorial.org/help">
    <%= t ".link_name_help" %>
  </a>.
  <%= t ".content_help_2" %>
  <a href="http://www.railstutorial.org/book">
    <em><%= t ".link_name_help_1" %></em>
  </a>.
</p>
<b>
  </br>
  </br>
  <%= link_to t("back"), root_path %>
</b>

app/views/static_pages/home.html.erb
<% provide :title, t(".title") %>
<div class="center jumbotron">
  <h1><%= t ".title_sample" %></h1>
  <h2>
    <%= t ".content_sample" %>
    <a href="http://www.railstutorial.org/">
      <%= t ".link_name_sample" %>
    </a>
    <%= t ".content_end_sample" %>
  </h2>
  <%= link_to t(".sign_up"), signup_path,
  class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"),
'http://rubyonrails.org/' %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: @user %>

  <%= f.label :name, t(".name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, t(".email") %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, t(".password") %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, t(".confirmation") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: Settings.user_picture_thumb_size %>
  <%= link_to user.name, @user %>
  <% if current_user.admin? && !user.current_user?(current_user) %>
    | <%= link_to t(".delete"), user, method: :delete,
                                      data: { confirm: t(".del_confirm") } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".button_text") %>
<h1><%= t ".content" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">
        <%= t ".link_change" %></a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t(".title") %>
<h1><% t ".title" %></h1>
<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, t(".sign_up") %>
<% provide :button_text, t(".button_text") %>
<h1><%= t ".sign_up" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>